"""empty message

Revision ID: 61013b90bee7
Revises: 
Create Date: 2022-11-12 15:24:20.746138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61013b90bee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('submit_times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessments')
    # ### end Alembic commands ###
