"""empty message

Revision ID: 804418355dc3
Revises: 4d26f47cb153
Create Date: 2022-11-12 15:31:00.573188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804418355dc3'
down_revision = '4d26f47cb153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'submit_times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('submit_times', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
